apiVersion: v2
name: byparr
description: Byparr Helm Chart - FlareSolverr drop-in replacement using Camoufox
type: application
version: 0.1.2
appVersion: "latest"
home: https://github.com/ThePhaseless/Byparr
sources:
  - https://github.com/ThePhaseless/Byparr
maintainers:
  - name: Saran
    email: saranmovva@gmail.com
dependencies:
  - name: common
    repository: oci://oci.trueforge.org/truecharts
    version: 29.1.7
