image:
  repository: ghcr.io/thephaseless/byparr
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    controller: main
    ports:
      main:
        port: 8191
        protocol: http
        targetPort: 8191

ingress:
  main:
    enabled: false
    ingressClassName: ""
    hosts:
      - host: byparr.example.com
        paths:
          - path: /
            pathType: Prefix
    tls: []
    # tls:
    #   - hosts:
    #       - byparr.example.com
    #     secretName: byparr-tls
    targetSelector:
      main: main
    integrations:
      traefik:
        enabled: false
      nginx:
        enabled: false
      certManager:
        enabled: false
        # certificateIssuer: ""

workload:
  main:
    enabled: true
    type: Deployment
    podSpec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        main:
          enabled: true
          primary: true
          imageSelector: image